apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nutexporter.name" . }}
  labels:
    {{- include "nutexporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "nutexporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nutexporter.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      containers:
        - name: nut-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraArgs }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            privileged: true
          ports:
          - containerPort: 9199
            name: http
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /ups_metrics
              port: http
            initialDelaySeconds: 10
            failureThreshold: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /ups_metrics
              port: http
            initialDelaySeconds: 10
            failureThreshold: 5
            timeoutSeconds: 2
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 24Mi
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
