{{- if .Values.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "nutexporter.name" . }}-rules
  labels:
    {{- include "nutexporter.labels" . | nindent 4 }}
    {{- with .Values.rules.labels  }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: NutExporter
    rules: 
      {{- toYaml .Values.rules.rules | nindent 6 }}
{{- end }}
