apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "nutexporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels  }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "nutexporter.name" . }}
  namespace: {{ $.Values.serviceMonitor.namespace }}
spec:
  endpoints:
  - interval: 15s
    {{- with $.Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{ toYaml . | nindent 6}}
    {{- end }}
    {{- with $.Values.serviceMonitor.relabelings }}
    relabelings:
      {{ toYaml . | nindent 6}}
    {{- end }}
    path: /ups_metrics
    port: http
    scheme: http
  jobLabel: nut-exporter
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "nutexporter.selectorLabels" . | nindent 6 }}
