apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nut-exporter.fullname" . }}
  labels: 
    {{- include "nut-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
